name: Deploy web app

on:
  push:
    branches:
      - main

jobs:
  test-deploy:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --no-fund --no-audit

      - name: Run tests
        run: npm test

      - name: Deploy to Apache root
        run: |
          rsync -az --delete src/ /var/www/lab1/
